<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IB-Pune-LAP-329" failures="1" tests="11" name="com.Digitalcodes.testcases.Title_SectionPage_Test" time="167.979" errors="1" timestamp="2023-11-16T13:58:17 IST" skipped="2">
  <testcase classname="com.Digitalcodes.testcases.Title_SectionPage_Test" name="TC18_verifyDeleteBookmark_FromSection" time="8.938">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertFalse(Assert.java:78)
at org.testng.Assert.assertFalse(Assert.java:88)
at com.Digitalcodes.utilities.Baseclass.assertFalse(Baseclass.java:299)
at com.Digitalcodes.testcases.Title_SectionPage_Test.TC18_verifyDeleteBookmark_FromSection(Title_SectionPage_Test.java:429)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC18_verifyDeleteBookmark_FromSection -->
  <system-out/>
  <testcase classname="com.Digitalcodes.testcases.Title_SectionPage_Test" name="TC11_verifyPrintSection_FromSection" time="1.735"/>
  <system-out/>
  <testcase classname="com.Digitalcodes.testcases.Title_SectionPage_Test" name="TC17_verifyEditBookmark_FromSection" time="7.515"/>
  <system-out/>
  <testcase classname="com.Digitalcodes.testcases.Title_SectionPage_Test" name="TC15_verifyDeleteNotes_FromSection" time="0.028">
    <skipped/>
  </testcase> <!-- TC15_verifyDeleteNotes_FromSection -->
  <system-out/>
  <testcase classname="com.Digitalcodes.testcases.Title_SectionPage_Test" name="TC14_verifyEditNotes_FromSection" time="0.044">
    <skipped/>
  </testcase> <!-- TC14_verifyEditNotes_FromSection -->
  <system-out/>
  <testcase classname="com.Digitalcodes.testcases.Title_SectionPage_Test" name="TC09_verifyCreateNotes_atSection" time="33.775"/>
  <system-out/>
  <testcase classname="com.Digitalcodes.testcases.Title_SectionPage_Test" name="TC10_verifyCreateBookmark_atSection" time="39.985"/>
  <system-out/>
  <testcase classname="com.Digitalcodes.testcases.Title_SectionPage_Test" name="TC11_verifyShareSection_FromSection" time="19.918"/>
  <system-out/>
  <testcase classname="com.Digitalcodes.testcases.Title_SectionPage_Test" name="TC13_verifyShareNote_FromSction" time="0.004">
    <error message="
[public void com.Digitalcodes.testcases.Title_SectionPage_Test.TC13_verifyShareNote_FromSction(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: TC13_verifyShareNote_FromSction([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4])
Arguments: [(java.lang.String) Browse Contents,(java.lang.String) I-Codes,(java.lang.String) 2021 I-Codes,(java.lang.String) 2021 International Building Code (IBC),(java.lang.String) CHAPTER 2 DEFINITIONS,(java.lang.String) PREMIUM]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.Digitalcodes.testcases.Title_SectionPage_Test.TC13_verifyShareNote_FromSction(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.lang.Exception] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: TC13_verifyShareNote_FromSction([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4])
Arguments: [(java.lang.String) Browse Contents,(java.lang.String) I-Codes,(java.lang.String) 2021 I-Codes,(java.lang.String) 2021 International Building Code (IBC),(java.lang.String) CHAPTER 2 DEFINITIONS,(java.lang.String) PREMIUM]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC13_verifyShareNote_FromSction -->
  <system-out/>
  <testcase classname="com.Digitalcodes.testcases.Title_SectionPage_Test" name="TC16_verifyShareBookmark_FromSection" time="25.987"/>
  <system-out/>
  <testcase classname="com.Digitalcodes.testcases.Title_SectionPage_Test" name="TC19_verifyLinksOnChapter" time="30.050"/>
  <system-out/>
</testsuite> <!-- com.Digitalcodes.testcases.Title_SectionPage_Test -->
